backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

use common\models\File;
use common\models\Folder;
use common\models\User;
use common\models\UserFolder;
use common\models\UploadMyFile;
use common\models\Login;
use common\models\SignUpForm;

class SiteController extends Controller
{

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => [
							'signup',
							'login',
							'error'
						],
						'allow' => true,
					],
					[
						'actions' => [
							'logout',
							'index',
							'myfiles',
							'add-folder',
							'folder',
							'down',
							'create',
							'update',
							'delete',
						],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = File::find()->orderBy(['date' => SORT_DESC]);
		return $this->render('index', [
			'model' => $model
		]);
	}

	public function actionMyfiles() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = File::find()->where(['user_id' => Yii::$app->user->id])
							->orderBy(['date' => SORT_DESC]);

		return $this->render('myfiles', [
			'model' => $model
		]);
	}

	public function actionFolder($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();
		$folder = Folder::find()->where(['id' => $id])->one();
		$model = File::find()->where(['folder_id' => $id]);
		return $this->render('folder', [
			'folder' => $folder,
			'model' => $model
		]);
	}

	public function actionCreate() {

		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new File();

		if (Yii::$app->request->isPost) {
			$file = UploadedFile::getInstance($model, 'hash_name');
			// var_dump(Yii::$app->request->post());die;
			if($model->saveFile($file, Yii::$app->request->post()['File']['folder_id'])) {
				return $this->redirect(['/site/myfiles']);
			}
		}

		$folders = [];
		$all_folders = Folder::find()->all();

		for ($i=0; $i < count($all_folders); $i++)
			$folders[$all_folders[$i]->id] = $all_folders[$i]->title;

		return $this->render('create', [
			'model' => $model,
			'folders' => $folders,
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = File::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionDown($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$file = File::findIdentity($id);
		
		if ($file->fileExists()) {
			$this->file_force_download($file->getFilePath(), $file->name);
			$file->count_downs += 1;
			$file->save(false);
		}

		// return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
	}



	public function actionAddFolder() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Folder();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Folder']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-folder', [
			'model' => $model,
		]);
	}

	public function actionSignup() {

		$this->layout = 'login';

		$model = new SignUpForm();

		if(isset($_POST['SignUpForm'])) {
			$model->attributes = Yii::$app->request->post('SignUpForm');
			if($model->validate() && $model->signup()) {
				return $this->redirect(['login']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		
		$this->layout = 'login';

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			$user = $model->getUser();
			if($model->validate()) {
				if($user->isAdmin($user['id'])) {
					Yii::$app->user->login($user);
					return $this->goHome();
				}
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	private function file_force_download($file, $name) {
		if (file_exists($file)) {
			// сбрасываем буфер вывода PHP, чтобы избежать переполнения памяти выделенной под скрипт
			// если этого не сделать файл будет читаться в память полностью!
			if (ob_get_level()) {
				ob_end_clean();
			}
			// заставляем браузер показать окно сохранения файла
			header('Content-Description: File Transfer');
			header('Content-Type: application/octet-stream');
			header('Content-Disposition: attachment; filename=' . basename($name));
			header('Content-Transfer-Encoding: binary');
			header('Expires: 0');
			header('Cache-Control: must-revalidate');
			header('Pragma: public');
			header('Content-Length: ' . filesize($file));
	    // читаем файл и отправляем его пользователю
			if ($fd = fopen($file, 'rb')) {
				while (!feof($fd)) {
					print fread($fd, 1024);
				}
				fclose($fd);
			} else {
				exit;
			}
		} else {
			exit;
		}
	}
}

backend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use yii\widgets\AlertLte;

?>
	  <!-- Content Wrapper. Contains page content -->
	  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
			<?php if (isset($this->blocks['content-header'])) { ?>
				<h1><?= $this->blocks['content-header'] ?></h1>
			<?php } else { ?>
				<h1>
					<?php
					if ($this->title !== null) {
						echo \yii\helpers\Html::encode($this->title);
					} else {
						echo \yii\helpers\Inflector::camel2words(
							\yii\helpers\Inflector::id2camel($this->context->module->id)
						);
						echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
					} ?>
				</h1>
			<?php } ?>

			<?=
			Breadcrumbs::widget([
				'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
			]) ?>
        </section>

        <!-- Main content -->
        <section class="content">
			<?= $content ?>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

backend/views/layouts/footer.php
<footer class="main-footer">
	Copyright &copy; 2017 Все права мои.
</footer>

backend/views/layouts/header.php
<?php
use yii\helpers\Html;
?>
<header class="main-header">
	<!-- Logo -->
	<a href="/" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini"><b><?=$title?></b></span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg"><b><?=$title?></b> Administrator</span>
	</a>
	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top" role="navigation">
		<!-- Sidebar toggle button-->
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">
				<!-- User Account: style can be found in dropdown.less -->
				<li class="dropdown user user-menu">
					<a href="/" class="dropdown-toggle" data-toggle="dropdown">
						<?= Html::img('@web/img/user2-160x160.jpg', ['class' => 'user-image', 'alt'=>'User Image']) ?>
						<span class="hidden-xs"><?= \Yii::$app->user->identity->username ?></span>
					</a>
					<ul class="dropdown-menu">
						<!-- User image -->
						<li class="user-header">
							<?= Html::img('@web/img/user2-160x160.jpg', ['class' => 'img-circle', 'alt'=>'User Image']) ?>
							<p>
								<?= \Yii::$app->user->identity->username ?> - The Вы
								<small></small>
							</p>
						</li>
						<!-- Menu Footer-->
						<li class="user-footer">
							<div class="pull-right">
								<a href="/admin/site/logout" class="btn btn-default btn-flat">Пока</a>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>

backend/views/layouts/leftside.php
<?php

use adminlte\widgets\Menu;
use yii\helpers\Html;
use yii\helpers\Url;

use common\models\Folder;

$folders = [];
$all_folders = Folder::find()->all();

for ($i=0; $i < count($all_folders); $i++) {
	$item = $all_folders[$i];
	$folders[] = [
		'label' => $item->title,
		'icon' => 'fa fa-folder',
		'url' => ["/site/folder?id=$item->id"],
		'active' => ($this->context->route == 'site/folder' and $_GET['id'] == $item->id)
	];
}

// var_dump($this->context->route); die;

?>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- Sidebar user panel -->
		<div class="user-panel">
			<div class="pull-left image">
				<?= Html::img('@web/img/user2-160x160.jpg', ['class' => 'img-circle', 'alt' => 'User Image']) ?>
			</div>
			<div class="pull-left info">
				<p><?= \Yii::$app->user->identity->username ?></p>
				<a href=""><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>
		<!-- sidebar menu: : style can be found in sidebar.less -->
		<?php // var_dump($folders) ?>
		<?=
			Menu::widget(
				[
					'options' => ['class' => 'sidebar-menu'],
					'items' => [
						['label' => 'Меню', 'options' => ['class' => 'header']],
						[
							'label' => 'Главная',
							'icon' => 'fa fa-home', 
							'url' => ['/'],
							'active' => $this->context->route == 'site/index'
						],
						[
							'label' => 'Ваши файлы',
							'icon' => 'fa fa-folder', 
							'url' => ['/site/myfiles'],
							'active' => $this->context->route == 'site/myfiles'
						],
						[
							'label' => 'Общие папки',
							'icon' => 'fa fa-folder',
							'url' => '#',
							'items' => $folders
						],
						[
							'label' => 'Добавить папку',
							'icon' => 'fa fa-plus', 
							'url' => ['/site/add-folder'],
							'active' => $this->context->route == 'site/add-folder'
						],
					],
				]
			)
		?>
		
	</section>
	<!-- /.sidebar -->
</aside>

backend/views/layouts/login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use backend\assets\AdminLteAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use backend\assets\AppAsset;
use backend\assets\AdminLteAsset;

//AppAsset::register($this);
$asset      = AdminLteAsset::register($this);
$baseUrl    = $asset->baseUrl;

use backend\assets\FontAwesomeAsset;
FontAwesomeAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>

<div class="wrapper">
    <?= $this->render('header.php', ['baserUrl' => $baseUrl, 'title'=>Yii::$app->name]) ?>
    <?= $this->render('leftside.php', ['baserUrl' => $baseUrl]) ?>
    <?= $this->render('content.php', ['content' => $content]) ?>
    <?= $this->render('footer.php', ['baserUrl' => $baseUrl]) ?>
    <?= $this->render('rightside.php', ['baserUrl' => $baseUrl]) ?>
</div>

<!--footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?//= date('Y') ?></p>

        <p class="pull-right"><?//= Yii::powered() ?></p>
    </div>
</footer-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>