backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

use common\models\File;
use common\models\Folder;
use common\models\User;
use common\models\UserFolder;
use common\models\UploadMyFile;
use common\models\Login;
use common\models\SignUpForm;

class SiteController extends Controller
{

	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => [
							'signup',
							'login',
							'error'
						],
						'allow' => true,
					],
					[
						'actions' => [
							'logout',
							'index',
							'myfiles',
							'add-folder',
							'folder',
							'down',
							'create',
							'update',
							'delete',
						],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = File::find()->orderBy(['date' => SORT_DESC]);
		return $this->render('index', [
			'model' => $model
		]);
	}

	public function actionMyfiles() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = File::find()->where(['user_id' => Yii::$app->user->id])
							->orderBy(['date' => SORT_DESC]);

		return $this->render('myfiles', [
			'model' => $model
		]);
	}

	public function actionFolder($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();
		$folder = Folder::find()->where(['id' => $id])->one();
		$model = File::find()->where(['folder_id' => $id]);
		return $this->render('folder', [
			'folder' => $folder,
			'model' => $model
		]);
	}

	public function actionCreate() {

		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new File();

		if (Yii::$app->request->isPost) {
			$file = UploadedFile::getInstance($model, 'hash_name');
			// var_dump(Yii::$app->request->post());die;
			if($model->saveFile($file, Yii::$app->request->post()['File']['folder_id'])) {
				return $this->redirect(['/site/myfiles']);
			}
		}

		$folders = [];
		$all_folders = Folder::find()->all();

		for ($i=0; $i < count($all_folders); $i++)
			$folders[$all_folders[$i]->id] = $all_folders[$i]->title;

		return $this->render('create', [
			'model' => $model,
			'folders' => $folders,
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = File::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionDown($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$file = File::findIdentity($id);
		
		if ($file->fileExists()) {
			$this->file_force_download($file->getFilePath(), $file->name);
			$file->count_downs += 1;
			$file->save(false);
		}

		// return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
	}



	public function actionAddFolder() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Folder();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Folder']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-folder', [
			'model' => $model,
		]);
	}

	public function actionSignup() {

		$this->layout = 'login';

		$model = new SignUpForm();

		if(isset($_POST['SignUpForm'])) {
			$model->attributes = Yii::$app->request->post('SignUpForm');
			if($model->validate() && $model->signup()) {
				return $this->redirect(['login']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		
		$this->layout = 'login';

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			$user = $model->getUser();
			if($model->validate()) {
				if($user->isAdmin($user['id'])) {
					Yii::$app->user->login($user);
					return $this->goHome();
				}
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	private function file_force_download($file, $name) {
		if (file_exists($file)) {
			// сбрасываем буфер вывода PHP, чтобы избежать переполнения памяти выделенной под скрипт
			// если этого не сделать файл будет читаться в память полностью!
			if (ob_get_level()) {
				ob_end_clean();
			}
			// заставляем браузер показать окно сохранения файла
			header('Content-Description: File Transfer');
			header('Content-Type: application/octet-stream');
			header('Content-Disposition: attachment; filename=' . basename($name));
			header('Content-Transfer-Encoding: binary');
			header('Expires: 0');
			header('Cache-Control: must-revalidate');
			header('Pragma: public');
			header('Content-Length: ' . filesize($file));
	    // читаем файл и отправляем его пользователю
			if ($fd = fopen($file, 'rb')) {
				while (!feof($fd)) {
					print fread($fd, 1024);
				}
				fclose($fd);
			} else {
				exit;
			}
		} else {
			exit;
		}
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class SiteController extends Controller {

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
		];
	}

	public function actionIndex() {
		return $this->redirect(['admin/']);
	}


}

backend/views/site/add-folder.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Новая папка');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"></div>
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

				<div class="form-group center">
					<?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' =>  'btn btn-success']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/create.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Загрузка файлов');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"></div>
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'hash_name')->fileInput(['maxlength' => true]) ?>
				<?= $form->field($model, 'folder_id')->dropDownList($folders) ?>

				<div class="form-group center">
					<?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' =>  'btn btn-success']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/folder.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', $folder->title);
$this->params['breadcrumbs'][] = $this->title;

$dataProvider = new ActiveDataProvider([
	'query' => $model,
	'pagination' => [
	 'pageSize' => 20,
	],
]);

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">

			<div class="contact-index">
					<?= Html::a(Yii::t('app','Добавить'), Url::base() . '/site/create') ?>
				<div class="fa-br"></div>
				<br>
				<?php
				echo GridView::widget([
					'dataProvider' => $dataProvider,
					'layout' => "{items}\n{pager}",
					'columns' => [
						'name',
						'date',
						'type',
						'count_downs',
						[
							'attribute' => 'user',
							'format' => 'raw',
							'value' => function($data){
								return User::find()->where(['id' => $data->user_id])->one()->username;
							},
						],
						[
							'label' => 'Ссылка',
							'format' => 'raw',
							'value' => function($data){
								return  Html::a(Yii::t('app',' Скачать'), [ '/site/down', 'id' => $data->id]);
							},
						],
					],
				]);
				?>

			</div>

		</div>
	</div>
</div>

backend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Последние загруженные файлы');
$this->params['breadcrumbs'][] = $this->title;

$dataProvider = new ActiveDataProvider([
	'query' => $model,
	'pagination' => [
	 'pageSize' => 20,
	],
]);

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">

<div class="contact-index">
		<?= Html::a(Yii::t('app','Добавить'), Url::base() . '/site/create') ?>
	<div class="fa-br"></div>
	<br>
	<?php
	echo GridView::widget([
		'dataProvider' => $dataProvider,
		'layout' => "{items}\n{pager}",
		'columns' => [
			'name',
			'date',
			'type',
			'count_downs',
			[
				'attribute' => 'user',
				'format' => 'raw',
				'value' => function($data){
					return User::find()->where(['id' => $data->user_id])->one()->username;
				},
			],
			[
				'label' => 'Ссылка',
				'format' => 'raw',
				'value' => function($data){
					return  Html::a(Yii::t('app',' Скачать'), [ '/site/down', 'id' => $data->id]);
				},
			],
		],
	]);
	?>

</div>

		</div>
	</div>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<div class="row">
		<div class="login-box">
			<div class="col-md-12 box box-radius">
			<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

				<?= $form->field($model, 'email', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-user"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->textInput(['autofocus' => true])
								->input('text', ['placeholder'=>'email']) ?>

				<?= $form->field($model, 'password', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-lock"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->passwordInput()
								->input('password', ['placeholder'=>'Password'])?>

				<div class="form-group">
					<?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
					<hr>
					<?= Html::a('Регистрация', ['/site/signup'],['class' => 'btn']) ?>
				</div>

			<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/myfiles.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Ваши файлы');
$this->params['breadcrumbs'][] = $this->title;

$dataProvider = new ActiveDataProvider([
	'query' => $model,
	'pagination' => [
	 'pageSize' => 20,
	],
]);

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">

<div class="contact-index">
		<?= Html::a(Yii::t('app','Добавить'), Url::base() . '/site/create') ?>
	<div class="fa-br"></div>
	<br>
	<?php
	echo GridView::widget([
		'dataProvider' => $dataProvider,
		'layout' => "{items}\n{pager}",
		'columns' => [
			// ['class' => 'yii\grid\SerialColumn'],
			'name',
			'date',
			'type',
			'count_downs',
			[
				'attribute' => 'user',
				'format' => 'raw',
				'value' => function($data){
					return User::find()->where(['id' => $data->user_id])->one()->username;
				},
			],
			[
				'label' => 'Ссылка',
				'format' => 'raw',
				'value' => function($data){
					return  Html::a(Yii::t('app',' Скачать'), [ '/site/down', 'id' => $data->user_id]);
				},
			],
			[
				'class' => 'yii\grid\ActionColumn',
				'header'=>'Действия', 
				'headerOptions' => ['width' => '80'],
				'template' => '{delete}',
			],
		],
	]);
	?>

</div>

		</div>
	</div>
</div>

backend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<div class="row">
		<div class="login-box">
			<div class="col-md-12 box box-radius">
			<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

				<?= $form->field($model, 'username', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-user"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->textInput(['autofocus' => true])
								->input('text', ['placeholder'=>'Логин']) ?>

				<?= $form->field($model, 'email', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-user"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->textInput()
								->input('text', ['placeholder'=>'email']) ?>

				<?= $form->field($model, 'password', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-lock"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->passwordInput()
								->input('password', ['placeholder'=>'Пароль'])?>

				<div class="form-group">
					<?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
					<hr>
					<?= Html::a('Войти', ['/site/login'],['class' => 'btn']) ?>
				</div>

			<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/update.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Кандидаты');

$status = '';
?>
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading"><?= $model->title ?></div>
        <div class="panel-body">

<?php



$this->title = Yii::t('app', 'Update');

$this->params['breadcrumbs'][] = ['label' => 'Записи'];
$this->params['breadcrumbs'][] = ['label' => $model->title];
?>
<div class="link-update">

	<?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'title')->textInput(['placeholder' => '']) ?>
	<?= $form->field($model, 'desc')->textArea(['placeholder' => '']) ?>
	<?= $form->field($model, 'left_side')->dropDownList($sides, ['disabled' => 'disabled']) ?>
	<?= $form->field($model, 'right_side')->dropDownList($sides, ['disabled' => 'disabled']) ?>
	<?= $form->field($model, 'status')->dropDownList([
		'1' => 'Активен',
		'0' => 'Завершен',
	]) ?>


	<div class="form-group center">
		<?= ''// Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
		<?= Html::submitButton(Yii::t('app', 'Update'), ['class' =>  'btn btn-success']) ?>
	</div>
	<?php ActiveForm::end(); ?>


</div>

        </div>
    </div>
</div>